# Generated by Django 3.2 on 2021-04-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='dorixona.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Dorixona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('yuridik_nomi', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='logolar/')),
                ('ish_24_soat', models.BooleanField(default=True)),
                ('manzil', models.CharField(max_length=400)),
                ('telfon', models.CharField(max_length=13)),
                ('xolati', models.CharField(choices=[('faol', 'Faol'), ('nofaol', 'Nofaol'), ('tekshirilmagan', 'Tekshirilmagan')], default='tekshirilmagan', max_length=20)),
                ('uzunlik', models.CharField(max_length=50)),
                ('kenglik', models.CharField(max_length=50)),
                ('qoshilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorixonalar', to='dorixona.tuman')),
            ],
        ),
        migrations.CreateModel(
            name='Dori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dorixonalar', models.ManyToManyField(to='dorixona.Dorixona')),
            ],
        ),
    ]
