# Generated by Django 3.2 on 2021-04-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dori',
            options={'verbose_name_plural': 'Dorilar'},
        ),
        migrations.AlterModelOptions(
            name='dorixona',
            options={'verbose_name_plural': 'Dorixonalar'},
        ),
        migrations.AlterModelOptions(
            name='tuman',
            options={'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='viloyat',
            options={'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='telfon',
            field=models.CharField(max_length=20),
        ),
    ]
