# Generated by Django 3.2 on 2021-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0002_auto_20210429_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorixona',
            name='map_url',
            field=models.URLField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
