# Generated by Django 3.2 on 2021-04-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0003_dorixona_map_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dori',
            name='dorixonalar',
        ),
        migrations.AddField(
            model_name='dori',
            name='dorixona',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dorilar', to='dorixona.dorixona'),
            preserve_default=False,
        ),
    ]
