# Generated by Django 3.2 on 2021-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0004_auto_20210429_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorixona',
            name='kenglik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='uzunlik',
            field=models.CharField(max_length=100),
        ),
    ]
