# Generated by Django 3.2 on 2021-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0005_auto_20210501_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorixona',
            name='map_url',
            field=models.URLField(max_length=1000),
        ),
    ]
