# Generated by Django 3.2 on 2021-05-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0006_alter_dorixona_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dori',
            name='dorixona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorilar', to='dorixona.dorixona', verbose_name='dorixona'),
        ),
        migrations.AlterField(
            model_name='dori',
            name='narx',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='narx'),
        ),
        migrations.AlterField(
            model_name='dori',
            name='nomi',
            field=models.CharField(max_length=300, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='ish_24_soat',
            field=models.BooleanField(default=True, verbose_name='ish 24 soat'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='kenglik',
            field=models.CharField(max_length=100, verbose_name='kenglik'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='logo',
            field=models.ImageField(upload_to='logolar/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='manzil',
            field=models.CharField(max_length=400, verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='nomi',
            field=models.CharField(max_length=300, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='qoshilgan',
            field=models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan"),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='telfon',
            field=models.CharField(max_length=20, verbose_name='telfon'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorixonalar', to='dorixona.tuman', verbose_name='tuman'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='uzunlik',
            field=models.CharField(max_length=100, verbose_name='uzunlik'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='xolati',
            field=models.CharField(choices=[('faol', 'Faol'), ('nofaol', 'Nofaol'), ('tekshirilmagan', 'Tekshirilmagan')], default='tekshirilmagan', max_length=20, verbose_name='xolati'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='yangilangan',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='yuridik_nomi',
            field=models.CharField(max_length=300, verbose_name='yuridik nomi'),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='nomi',
            field=models.CharField(max_length=200, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='dorixona.viloyat', verbose_name='viloyat'),
        ),
        migrations.AlterField(
            model_name='viloyat',
            name='nomi',
            field=models.CharField(max_length=200, verbose_name='nomi'),
        ),
    ]
