# Generated by Django 3.2.2 on 2021-05-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona', '0007_auto_20210506_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dori',
            name='dorixona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorilar', to='dorixona.dorixona'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='ish_24_soat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='kenglik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='logo',
            field=models.ImageField(upload_to='logolar/'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='manzil',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='nomi',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='qoshilgan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='telfon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorixonalar', to='dorixona.tuman'),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='uzunlik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='xolati',
            field=models.CharField(choices=[('faol', 'Faol'), ('nofaol', 'Nofaol'), ('tekshirilmagan', 'Tekshirilmagan')], default='tekshirilmagan', max_length=20),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='yangilangan',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dorixona',
            name='yuridik_nomi',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='dorixona.viloyat'),
        ),
    ]
